//
// Created by Haidy on 2020/6/16.
//

#ifndef NETWORK_TCP_STATUS_H
#define NETWORK_TCP_STATUS_H

#define TCP_STATUS_LISTEN 0
#define TCP_STATUS_SYN_SENT 1
#define TCP_STATUS_ESTABLISHED 2
#define TCP_STATUS_FIN_WAIT_1 3
#define TCP_STATUS_FIN_WAIT_2 4
#define TCP_STATUS_TIME_WAIT 5

#define TCP_STATUS_SYN_RECV 6
#define TCP_STATUS_CLOSE_WAIT 7
#define TCP_STATUS_LAST_ACK 8
#define TCP_STATUS_CLOSED 9

#endif //NETWORK_TCP_STATUS_H
